version: '2'

networks:
  kafka-net:
    driver: bridge
services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    expose:
      - '9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_LISTENERS= PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE= 'false'
    depends_on:
      - zookeeper-server

  # kafka-server2:
  #   image: 'bitnami/kafka:latest'
  #   networks:
  #     - kafka-net    
  #   ports:
  #     - '9092:9094'
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9094
  #   depends_on:
  #     - zookeeper-server